### ISSUE TITLE
add external module mechanism

### ISSUE THREAD

**Issue by YusukeSuzuki** [YusukeSuzuki/Larix#2]
project.yaml like this

```

---
targets:
  - name: default 
    target_template: makefile
    output_file_name: test
    source_files:
      - src/*.c
    external_modules:
      - libccv
      - libbz2
```
